### ISSUE TITLE
Gensim version

### ISSUE THREAD

**Issue by IslamMohamedMosaad** [bakrianoo/aravec#1]
Could you please state the version of Gensim as every time i run the code i get the following error:

> AttributeError: 'module' object has no attribute 'call_on_class_only'

**Comment by bakrianoo** [comment]
Hi

I built the first version on top of 2.3 version while the second on top of
3.2 version. I will update the info but please if it still returns you a
problem, send me your code .

**Comment by IslamMohamedMosaad** [comment]
get this error when use 3.2 version
>AttributeError: 'module' object has no attribute 'Word2VecKeyedVectors'

``# -*- coding: utf8 -*-
import gensim
import re
model = gensim.models.Word2Vec.load('tweets_cbow_300')

**Comment by bakrianoo** [comment]
Hi Eslam

It seems that gensim recommends all to update to 3.4 version. I just noticed that now.

https://github.com/RaRe-Technologies/gensim/issues/1882

I will attach a screenshot of my code using 3.4 version.
![w2v](https://user-images.githubusercontent.com/14326057/38176655-05b3cd8e-35f3-11e8-9be6-492a47a118af.jpg)

**Comment by IslamMohamedMosaad** [comment]
Thanks for ur great efforts .

**Comment by waadth** [comment]
I have the error "ValueError: cannot reshape array of size 191907498 into shape (1259756,300)" 
Only when I use this word embedding "full_uni_sg_300_twitter.mdl"
where other n-gram version work good 

<img width="1145" alt="‏لقطة الشاشة ٢٠١٩-٠٧-٠٣ في ٣ ٣٥ ٤١ ص" src="https://user-images.githubusercontent.com/44520276/60555097-a51cab80-9d43-11e9-9665-29d3d50ef5c2.png">
<img width="1145" alt="‏لقطة الشاشة ٢٠١٩-٠٧-٠٣ في ٣ ٣٦ ٠٣ ص" src="https://user-images.githubusercontent.com/44520276/60555111-b1086d80-9d43-11e9-9dbb-67829949393f.png">
