### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by lateef-k** [bakrianoo/aravec#12]
I get the following error:
```
<Error>
<Code>UserSuspended</Code>
<BucketName>bakrianoo</BucketName>
<RequestId>tx000000000000057c105c6-005f16fefe-95f8c6-sfo2a</RequestId>
<HostId>95f8c6-sfo2a-sfo</HostId>
</Error>
```

**Comment by bakrianoo** [comment]
We had some problems in serving the download links now, this problem could be solved in the next 7 days. I will notify you when the download links become ready again. Thanks

**Comment by lateef-k** [comment]
No problem. And thanks for making this open source, seriously. Not to go off on a tangent, but too few Arabic NLP resources are open source. Everything is proprietary and people wonder why the field is stagnant. We need more projects like this.

**Comment by bakrianoo** [comment]
The download links are ready now for downloading. Thanks for your report.
