### ISSUE TITLE
Unigram model Wikipedia-SkipGram Vec-Size 100 archive is corrupt

### ISSUE THREAD

**Issue by masalha-alaa** [bakrianoo/aravec#17]
When I try to unzip `full_uni_sg_100_wiki.zip` I get the following error message:

> Checksum error in `full_unit_sg_100_wiki\full_uni_sg_100_wiki.mdl.trainables.syn1neg.npy. The file is corrupt.
> The archive is corrupt.

On the other hand the model with the 300 Vec-Size `full_uni_sg_300_wiki` is extracted successfully.

**Comment by bakrianoo** [comment]
Hi @masalha-alaa 
Thanks for reporting the file
You can use thess temp links until I can fix the original ones.

https://bakrianoo.s3.us-west-2.amazonaws.com/aravec/full_uni_sg_100_wiki.zip
https://bakrianoo.s3.us-west-2.amazonaws.com/aravec/full_uni_sg_300_wiki.zip
