### ISSUE TITLE
what is the diffrence between the numpy array ?

### ISSUE THREAD

**Issue by adelabdelli** [bakrianoo/aravec#2]
i downloaded "tweets_cbow_300" and i found that there is  two numpy array and both are in float format and both have the same  shape but they don't have the same values ? so what is the difference  between them ?
--

**Comment by bakrianoo** [comment]
Hi

These are what hold the vectors. You just need load the third file which comes without any .extension. I hop this image could help you.

https://raw.githubusercontent.com/bakrianoo/aravec/master/how.jpg
