### ISSUE TITLE
Request for the datasets

### ISSUE THREAD

**Issue by AbubakrHassan** [bakrianoo/aravec#3]
Hello bakrianoo
Is the dataset you've collected available for academic purposes ? 
I'm more interested in the wikipedia articles
and thanks 😁

**Comment by bakrianoo** [comment]
Hi 

If you're interesting in Wikipedia dataset. Simply you could follow these steps:
1- Download the last Arabic dump of Wikipedia from here:
https://dumps.wikimedia.org/arwiki/latest/arwiki-latest-pages-articles.xml.bz2

2- Clone this repo project into your local machine
https://github.com/attardi/wikiextractor

3- Run this command [you'll reach the .py file within the repo you jsut downloaded]
WikiExtractor.py -o extracted -b 50M arwiki-latest-pages-articles.xml.bz2

Read more here : http://medialab.di.unipi.it/wiki/Wikipedia_Extractor

For the twitter dataset. I released a good sample of tweets to play with:
https://github.com/bakrianoo/Datasets/tree/master/Arabic%20Tweets
