### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by saja1994** [bakrianoo/aravec#5]
First of all thank you so much for your effort. But I need to ask you about how to convert your embeddings to be in a text file format like the available Glove embeddings for English?

Thanks,

**Comment by waadth** [comment]
hello,
I am writing a paper for word Embeddings effect on machine learning algorithm
my code is almost same this with little different https://github.com/iamaziz/ar-embeddings/blob/master/asa.py
I already use 2 type of word Embeddings for other authors with extension .bin

however, when I use "full_grams_sg_300_twitter.mdl" I have this error:

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-8-aeab99c23a2c> in <module>()
      5 dataset_path = "Sport_TrainingSet_1000_01.csv"
      6 # run
----> 7 ArSentiment(embeddings_path, dataset_path, plot_roc=True)
      8 

<ipython-input-7-97698640762b> in __init__(self, embeddings_file, dataset_file, plot_roc, split, detailed)
     12         self.split = split
     13 
---> 14         self.embeddings, self.dimension = self.load_vectors(embeddings_file)
     15 
     16         # read dataset

<ipython-input-7-97698640762b> in load_vectors(model_name, binary)
     66         """load the pre-trained embedding model"""
     67         if binary:
---> 68             w2v_model = KeyedVectors.load_word2vec_format(model_name, binary=True)
     69         else:
     70             w2v_model = gensim.models.Word2Vec.load(model_name)

/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py in load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)
   1436         return _load_word2vec_format(
   1437             cls, fname, fvocab=fvocab, binary=binary, encoding=encoding, unicode_errors=unicode_errors,
-> 1438             limit=limit, datatype=datatype)
   1439 
   1440     def get_keras_embedding(self, train_embeddings=False):

/anaconda3/lib/python3.7/site-packages/gensim/models/utils_any2vec.py in _load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)
    170     logger.info("loading projection weights from %s", fname)
    171     with utils.smart_open(fname) as fin:
--> 172         header = utils.to_unicode(fin.readline(), encoding=encoding)
    173         vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
    174         if limit:

/anaconda3/lib/python3.7/site-packages/gensim/utils.py in any2unicode(text, encoding, errors)
    353     if isinstance(text, unicode):
    354         return text
--> 355     return unicode(text, encoding, errors=errors)
    356 
    357 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by bakrianoo** [comment]
Hi. You can simply write all the embeddings into a txt file to use anywhere. I do not know if this could help you or not ?

```python
import gensim
import json

model = gensim.models.Word2Vec.load('model/tweets_sg_100')

# ----- Write to txt File

all_tokens_vecs = {}
for i in range(0,len(model.wv.index2word)):
    all_tokens_vecs[ model.wv.index2word[i] ] = model.wv[model.wv.index2word[i]]

res = open("model.txt", 'w', encoding='utf8')
res.write(json.dumps(all_tokens_vecs))
res.close()

# ---- Read
with open('model.txt', 'r', encoding='utf8') as content_file:
    all_tokens_vecs = json.loads(content_file.read())

print(all_tokens_vecs['محمد'])
```

**Comment by waadth** [comment]
thank you for your effort
I try to do same code for both "full_grams_sg_300_twitter.md"l and "full_grams_cbow_300_twitter.mdl"
and i had this error 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-535ffe9302a0> in <module>()
     12 
     13 res = open("model.txt", 'w', encoding='utf8')
---> 14 res.write(json.dumps(all_tokens_vecs))
     15 res.close()
     16 

/anaconda3/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

/anaconda3/lib/python3.7/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/anaconda3/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/anaconda3/lib/python3.7/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type ndarray is not JSON serializable

any help please?

**Comment by waadth** [comment]
thank you for your effort
I prefer to convert it to .bin extension 
however,
I try to do same code for both "full_grams_sg_300_twitter.mdl" and "full_grams_cbow_300_twitter.mdl"
and I had this error

TypeError Traceback (most recent call last)
in ()
12
13 res = open("model.txt", 'w', encoding='utf8')
---> 14 res.write(json.dumps(all_tokens_vecs))
15 res.close()
16

/anaconda3/lib/python3.7/json/init.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
229 cls is None and indent is None and separators is None and
230 default is None and not sort_keys and not kw):
--> 231 return _default_encoder.encode(obj)
232 if cls is None:
233 cls = JSONEncoder

/anaconda3/lib/python3.7/json/encoder.py in encode(self, o)
197 # exceptions aren't as detailed. The list call should be roughly
198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
200 if not isinstance(chunks, (list, tuple)):
201 chunks = list(chunks)

/anaconda3/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
255 self.key_separator, self.item_separator, self.sort_keys,
256 self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)
258
259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/anaconda3/lib/python3.7/json/encoder.py in default(self, o)
177
178 """
--> 179 raise TypeError(f'Object of type {o.class.name} '
180 f'is not JSON serializable')
181

TypeError: Object of type ndarray is not JSON serializable

any help to convert that .mdl file to .bin, please?
I would be very thankful?

**Comment by abeermohamed1** [comment]
> thank you for your effort
> I prefer to convert it to .bin extension
> however,
> I try to do same code for both "full_grams_sg_300_twitter.mdl" and "full_grams_cbow_300_twitter.mdl"
> and I had this error
> 
> TypeError Traceback (most recent call last)
> in ()
> 12
> 13 res = open("model.txt", 'w', encoding='utf8')
> ---> 14 res.write(json.dumps(all_tokens_vecs))
> 15 res.close()
> 16
> 
> /anaconda3/lib/python3.7/json/init.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
> 229 cls is None and indent is None and separators is None and
> 230 default is None and not sort_keys and not kw):
> --> 231 return _default_encoder.encode(obj)
> 232 if cls is None:
> 233 cls = JSONEncoder
> 
> /anaconda3/lib/python3.7/json/encoder.py in encode(self, o)
> 197 # exceptions aren't as detailed. The list call should be roughly
> 198 # equivalent to the PySequence_Fast that ''.join() would do.
> --> 199 chunks = self.iterencode(o, _one_shot=True)
> 200 if not isinstance(chunks, (list, tuple)):
> 201 chunks = list(chunks)
> 
> /anaconda3/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
> 255 self.key_separator, self.item_separator, self.sort_keys,
> 256 self.skipkeys, _one_shot)
> --> 257 return _iterencode(o, 0)
> 258
> 259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
> 
> /anaconda3/lib/python3.7/json/encoder.py in default(self, o)
> 177
> 178 """
> --> 179 raise TypeError(f'Object of type {o.class.name} '
> 180 f'is not JSON serializable')
> 181
> 
> TypeError: Object of type ndarray is not JSON serializable
> 
> any help to convert that .mdl file to .bin, please?
> I would be very thankful?



> thank you for your effort
> I prefer to convert it to .bin extension
> however,
> I try to do same code for both "full_grams_sg_300_twitter.mdl" and "full_grams_cbow_300_twitter.mdl"
> and I had this error
> 
> TypeError Traceback (most recent call last)
> in ()
> 12
> 13 res = open("model.txt", 'w', encoding='utf8')
> ---> 14 res.write(json.dumps(all_tokens_vecs))
> 15 res.close()
> 16
> 
> /anaconda3/lib/python3.7/json/init.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
> 229 cls is None and indent is None and separators is None and
> 230 default is None and not sort_keys and not kw):
> --> 231 return _default_encoder.encode(obj)
> 232 if cls is None:
> 233 cls = JSONEncoder
> 
> /anaconda3/lib/python3.7/json/encoder.py in encode(self, o)
> 197 # exceptions aren't as detailed. The list call should be roughly
> 198 # equivalent to the PySequence_Fast that ''.join() would do.
> --> 199 chunks = self.iterencode(o, _one_shot=True)
> 200 if not isinstance(chunks, (list, tuple)):
> 201 chunks = list(chunks)
> 
> /anaconda3/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
> 255 self.key_separator, self.item_separator, self.sort_keys,
> 256 self.skipkeys, _one_shot)
> --> 257 return _iterencode(o, 0)
> 258
> 259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
> 
> /anaconda3/lib/python3.7/json/encoder.py in default(self, o)
> 177
> 178 """
> --> 179 raise TypeError(f'Object of type {o.class.name} '
> 180 f'is not JSON serializable')
> 181
> 
> TypeError: Object of type ndarray is not JSON serializable
> 
> any help to convert that .mdl file to .bin, please?
> I would be very thankful?

@waadth Hi did you find a fix for the below error appreciated

 TypeError: Object of type ndarray is not JSON serializable
