### ISSUE TITLE
Hello ,

### ISSUE THREAD

**Issue by samreenkazi** [bakrianoo/aravec#8]
Hello
nice effort first of all,
how did u train ur model on unigrams and n-grams models, i am trying to do similar approach for my native(urdu) language , would appreciate if you share your code for creating similar results for urdu language
regards

**Comment by tarekeldeeb** [comment]
Hello Samreen,

I already share all my code.
Check: https://github.com/tarekeldeeb/DeepSpeech-Quran/blob/master/data/quran/commands.txt

Regards,

**Comment by bakrianoo** [comment]
@samreenkazi 

Detecting the Ngrams is derived using PMI collocations. Take a look at this resource:
http://www.nltk.org/howto/collocations.html
