### ISSUE TITLE
Arabic Sentence Embedding (AraSIF)

### ISSUE THREAD

**Issue by kmario23** [bakrianoo/aravec#9]
Hi,
 In case someone is interested in computing sentence embeddings for Arabic text, we have a recent WANLP paper titled [**Incremental Domain Adaptation for Neural Machine Translation in Low-Resource Settings**](https://sites.google.com/view/wanlp-2019/home#h.p_fZnYssGqEQYB) where we leveraged [AraVec](https://github.com/bakrianoo/aravec) (i.e. pre-trained model from this repo) and [SIF-Smooth Inverse Frequency](https://github.com/PrincetonML/SIF) approach for computing (300D) sentence embeddings.

The code for the whole procedure is publicly available on GitHub @ [DFKI-Interactive-Machine-Learning/AraSIF](https://github.com/DFKI-Interactive-Machine-Learning/AraSIF).

**Comment by bakrianoo** [comment]
Thank you @kmario23  
I hope if we could have the paper soon to stop at the methodology and the benchmarking results. I am  also interesting in providing a sentence embedding solution for Arabic.

**Comment by kmario23** [comment]
Hi @bakrianoo,
  Please find the official ACL paper here: [Incremental Domain Adaptation for Neural Machine Translation in Low-Resource Settings](https://www.aclweb.org/anthology/papers/W/W19/W19-4601/). Thanks!

**Comment by bakrianoo** [comment]
Thanks, @kmario23 for your interesting. It seems that you did a great job here. Keep on. I hope you good luck in the next works :)

**Comment by abdelrahmanelnaka** [comment]
![image](https://user-images.githubusercontent.com/47519250/81183751-d1cad080-8faf-11ea-8b8c-83a133af5bfc.png)

I'm getting a Unicode encode error while running the ./convert_word2vecmodel2glove_model.py script the error is: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>

@kmario23 Have you ever faced this, or maybe have a solution cause I cannot identify the problem here.

**Comment by kmario23** [comment]
Hey @abdelrahmanelnaka,
  Thanks for your interest in our work! Please address all the encountered issues in the code repo here [DFKI-Interactive-Machine-Learning/AraSIF](https://github.com/DFKI-Interactive-Machine-Learning/AraSIF). This will help us to look into the issues and fix them.

I haven't tested the code in Windows. Sorry about that. Based on your error traceback, it seems there is problem with encoding. You can fix this by explicitly specifying the encoding as 'utf-8' when you open the file for writing. More concretely, please try the following:

replace the line:

``` with open(os.path.join(args.glove_model_path, glove_model), 'w') as gf: ```

with

``` with open(os.path.join(args.glove_model_path, glove_model), 'w', encoding='utf-8') as gf: ```

That should do the trick.
